name: tests

on:
  push:
    paths-ignore:
      - "*.md"
      - "*.mdx"
      - ".github/workflows/**"
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths-ignore:
      - "*.md"
      - "*.mdx"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Configure Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install 'pre-commit>=3.2.0,<4.0.0'

      - name: Check pre-commit
        run: python -m pre_commit run --all-files

  tests:
    name: Test
    needs: Validate
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        include:
          - os: ubuntu-20.04
            python_version: "3.6"
          - os: windows-2019
            python_version: "3.6"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Configure Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install -U build pip setuptools
          python -m pip install -U -r requirements.txt

      - name: Build sdist
        run: |
          python -m build --sdist

      - name: Delete source directory and .egg-info
        run: |
          rm -rf weasel *.egg-info
        shell: bash

      - name: Uninstall all packages
        run: |
          python -m pip freeze > installed.txt
          python -m pip uninstall -y -r installed.txt

      - name: Install from sdist
        run: |
          SDIST=$(python -c "import os;print(os.listdir('./dist')[-1])" 2>&1)
          python -m pip install dist/$SDIST
        shell: bash

      - name: Test import
        run: python -W error -c "import weasel"

      - name: "Install test requirements"
        run: |
          python -m pip install -r requirements.txt

      - name: "Run CPU tests"
        run: |
          python -m pytest --pyargs weasel
